export type Rom = {
  slug: string
  name: string
  type: "rom" | "os" | "tools"
  tagline: string
  description: string
  longDescription: string
  benefits: string[]
  features: string[]
  color: string
  bgColor: string
  borderColor: string
  ringColor: string
  url: string
  icon: string
}

export const roms: Rom[] = [
  {
    slug: "crdroid",
    name: "crDroid",
    type: "rom",
    tagline: "Performance & reliability over stock",
    description:
      "crDroid is a custom ROM based on LineageOS that aims to improve performance, reliability and customizability without compromising security.",
    longDescription:
      "crDroid is designed for users who want the best performance from their device without sacrificing reliability. Built on top of LineageOS, crDroid adds a wealth of customization options while maintaining the stability and security that users expect. Whether you're a power user looking to tweak every aspect of your phone or someone who wants a smoother daily experience, crDroid delivers.",
    benefits: [
      "Improved system performance and battery life compared to stock ROMs",
      "Regular security updates to keep your device safe",
      "Active community of developers and maintainers",
      "Support for a wide range of devices",
      "Balance between customization and stability",
    ],
    features: [
      "Status Bar & QS customization",
      "Lock screen personalization",
      "Gesture & button navigation",
      "Dark mode & UI theming",
      "Notification & sound control",
      "Game mode & smart charging",
    ],
    color: "text-coral",
    bgColor: "bg-coral/10",
    borderColor: "border-coral/20",
    ringColor: "ring-coral/30",
    url: "https://crdroid.net/",
    icon: "/crom-logos/rom/crdroid.png",
  },
  {
    slug: "lineageos",
    name: "LineageOS",
    type: "rom",
    tagline: "Free & open-source for all devices",
    description:
      "A free and open-source operating system for various devices based on the Android mobile platform, extending functionality and lifespan.",
    longDescription:
      "LineageOS is the most widely used custom Android ROM in the world. It extends the life of devices from over 20 different manufacturers, giving them a new lease on life with modern Android versions. Built by a passionate open-source community, LineageOS focuses on privacy, security, and user freedom while providing a clean and familiar Android experience.",
    benefits: [
      "Extends device lifespan — supports devices over 5 years old",
      "Monthly security patches — among the fastest in custom ROMs",
      "Trust system for transparent privacy and security monitoring",
      "Huge community with official support for 100+ devices",
      "Clean, near-stock Android experience with useful additions",
    ],
    features: [
      "User personalization focus",
      "Monthly security updates",
      "Trust security monitoring",
      "20+ manufacturer support",
      "Open-source apps & tools",
      "Enhanced dev debugging",
    ],
    color: "text-zen-blue",
    bgColor: "bg-zen-blue/10",
    borderColor: "border-zen-blue/20",
    ringColor: "ring-zen-blue/30",
    url: "https://lineageos.org/",
    icon: "/crom-logos/rom/lineageos.png",
  },
  {
    slug: "evolution-x",
    name: "Evolution X",
    type: "rom",
    tagline: "Pixel UI with deep customization",
    description:
      "Replicates the Google Pixel experience with added customization, based on LineageOS and built to bring Android 16 to your device.",
    longDescription:
      "Evolution X brings the best of Google's Pixel software to a wide range of devices. It combines the clean, polished Pixel UI with deep customization options that let you make your device truly yours. With frequent updates, strong security practices, and an active development community, Evolution X is the go-to ROM for users who want a premium Pixel-like experience without buying a Pixel.",
    benefits: [
      "Authentic Google Pixel UI and features on any supported device",
      "Frequent OTA updates with latest security patches",
      "Deep customization engine beyond what Pixel offers",
      "Based on LineageOS for a rock-solid stable foundation",
      "Optimized for both performance and battery efficiency",
    ],
    features: [
      "Google Pixel look & feel",
      "Latest security patches",
      "Deep customization options",
      "LineageOS stable base",
      "Performance & battery tuned",
      "Active community support",
    ],
    color: "text-zen-green",
    bgColor: "bg-zen-green/10",
    borderColor: "border-zen-green/20",
    ringColor: "ring-zen-green/30",
    url: "https://evolution-x.org/",
    icon: "/crom-logos/rom/evolution-x.png",
  },
  {
    slug: "pixel-experience",
    name: "Pixel Experience",
    type: "rom",
    tagline: "Pure Google Pixel feel on any device",
    description:
      "A ROM based on AOSP that aims to provide the exact Google Pixel experience, with all Pixel features and minimal modifications.",
    longDescription:
      "Pixel Experience is a custom Android ROM that brings the authentic Google Pixel experience to a wide range of devices. Based on AOSP (Android Open Source Project), it focuses on delivering the stock Pixel look, feel, and features with minimal modifications. It's the go-to choice for users who want their non-Pixel device to feel exactly like a Google Pixel.",
    benefits: [
      "True Google Pixel experience on non-Pixel devices",
      "All Pixel-exclusive features and apps included",
      "Clean, bloatware-free system",
      "Regular updates with security patches",
      "Great for users who prefer stock Android",
    ],
    features: [
      "Pixel Launcher & wallpapers",
      "Pixel sounds & ringtones",
      "Google Camera integration",
      "At a Glance widget",
      "Now Playing support",
      "Stock Android stability",
    ],
    color: "text-zen-purple",
    bgColor: "bg-zen-purple/10",
    borderColor: "border-zen-purple/30",
    ringColor: "ring-zen-purple/30",
    url: "https://get.pixelexperience.org/",
    icon: "/crom-logos/rom/pixel-experience.png",
  },
  {
    slug: "pixelos",
    name: "PixelOS",
    type: "rom",
    tagline: "AOSP with Pixel goodies & performance",
    description:
      "An AOSP-based ROM with Google apps included and all Pixel goodies, providing an experience similar to Google Pixel phones.",
    longDescription:
      "PixelOS is an AOSP-based ROM that comes with Google apps included and all Pixel goodies. It aims to provide an experience similar to Google Pixel phones with numerous performance enhancements and a small amount of useful additional features. It's perfect for users who want the Pixel experience with added performance tweaks.",
    benefits: [
      "Google apps included out of the box",
      "All Pixel goodies and features",
      "Performance enhancements over stock Pixel ROM",
      "Small but useful set of additional features",
      "Clean, lightweight AOSP base",
    ],
    features: [
      "Pixel Launcher with Google Discover",
      "Google Camera & Pixel apps included",
      "Performance-optimized kernel",
      "Useful additional customization",
      "Monthly security updates",
      "Active development community",
    ],
    color: "text-zen-teal",
    bgColor: "bg-zen-teal/10",
    borderColor: "border-zen-teal/30",
    ringColor: "ring-zen-teal/30",
    url: "https://pixelos.net/",
    icon: "/crom-logos/rom/pixelos.png",
  },
  {
    slug: "nusantara",
    name: "Nusantara ROM",
    type: "rom",
    tagline: "Android OS dari Nusantara untuk siapa saja",
    description:
      "A clean, bloatware-free Android ROM developed with enthusiasm from Indonesia, focusing on privacy and customization.",
    longDescription:
      "Nusantara ROM is an Android operating system developed from Nusantara (Indonesia) for everyone. It focuses on delivering a clean, bloatware-free experience with useful customizations from various trusted sources. Developed by passionate developers, it gives users full control over their device with no ads, no bloatware, and a clean interface — all completely free.",
    benefits: [
      "Completely bloatware-free and ad-free experience",
      "Developed by passionate, experienced developers",
      "Features curated from trusted sources",
      "Full user control over device privacy",
      "Free and open-source — no cost ever",
    ],
    features: [
      "Clean, bloatware-free interface",
      "Customization from trusted sources",
      "Privacy-first approach",
      "Active Indonesian development community",
      "Regular updates & improvements",
      "Free for everyone",
    ],
    color: "text-zen-orange",
    bgColor: "bg-zen-orange/10",
    borderColor: "border-zen-orange/30",
    ringColor: "ring-zen-orange/30",
    url: "https://nusantararom.org/",
    icon: "/crom-logos/rom/nusantara.png",
  },
  {
    slug: "project-elixir",
    name: "Project Elixir",
    type: "rom",
    tagline: "Redefine simplicity with minimalistic design",
    description:
      "A clean and minimal AOSP-based custom ROM focusing on stock Android with thoughtful, balanced enhancements.",
    longDescription:
      "Project Elixir is a clean and minimal AOSP-based custom ROM that focuses on delivering the best of stock Android with thoughtful, balanced enhancements. Designed for users who value stability, performance, and clean UI, Elixir eliminates unnecessary bloat while still offering meaningful customization features. Built by experienced developers, it brings Android 16 with a minimalist design and the perfect balance of customization options.",
    benefits: [
      "Clean AOSP base with Pixel-like UI/UX",
      "Lightweight and optimized for daily use",
      "Monthly updates with security patches",
      "Smooth performance & battery efficiency",
      "Strong privacy and security focus",
    ],
    features: [
      "Minimalist design with stock Android feel",
      "iOS-inspired automated depth clock",
      "Perfectly balanced customization",
      "Android 16 (Baklava) based",
      "Optimized for daily driver use",
      "Experienced development team",
    ],
    color: "text-zen-pink",
    bgColor: "bg-zen-pink/10",
    borderColor: "border-zen-pink/30",
    ringColor: "ring-zen-pink/30",
    url: "https://projectelixiros.com/",
    icon: "/crom-logos/rom/project-elixir.png",
  },
  {
    slug: "derpfest",
    name: "DerpFest",
    type: "rom",
    tagline: "Feature-rich AOSP with community-driven features",
    description:
      "An AOSP-based custom ROM twisted with the latest features from all over the Android development community.",
    longDescription:
      "DerpFest is an AOSP-based custom ROM that incorporates the best features from across the Android development community. Quality and stability are top priorities, bringing you the best Android has to offer. Now supporting Android 16 QPR2 with the latest security patches from Google, DerpFest continues to be one of the last open source custom ROMs still contributing code to the community.",
    benefits: [
      "Latest Android 16 QPR2 with Google security patches",
      "Features curated from across the Android community",
      "Strong focus on quality and stability",
      "One of the last truly open-source ROMs",
      "Active development with frequent updates",
    ],
    features: [
      "Latest Android 16 QPR2 base",
      "Community-driven feature set",
      "Quality & stability first approach",
      "Unique DerpFest contributions",
      "Wide device support",
      "Active Telegram community",
    ],
    color: "text-zen-yellow",
    bgColor: "bg-zen-yellow/10",
    borderColor: "border-zen-yellow/30",
    ringColor: "ring-zen-yellow/30",
    url: "https://derpfest.org/",
    icon: "/crom-logos/rom/derpfest.png",
  },
  {
    slug: "blissroms",
    name: "BlissRoms",
    type: "rom",
    tagline: "Open-source OS focused on design, usability & security",
    description:
      "An open-source Android-based OS delivering a harmonious blend of customization, security, and performance across a wide range of devices.",
    longDescription:
      "BlissRoms is an open-source Android-based operating system built to deliver a harmonious blend of customization, security, and performance across a wide range of devices. Started in 2014 and based on LineageOS, BlissRoms focuses on bringing the open-source community a quality OS that can run on all your devices as a daily driver, syncing your apps, settings, and customizations across all platforms.",
    benefits: [
      "Harmonious blend of customization, security & performance",
      "Based on LineageOS for a rock-solid foundation",
      "Cross-platform support — phones, laptops & PCs",
      "Daily driver quality with synced customizations",
      "Active development since 2014",
    ],
    features: [
      "Deep customization options",
      "Enhanced security features",
      "Performance optimizations",
      "Cross-platform compatibility",
      "LineageOS stable base",
      "Active community support",
    ],
    color: "text-zen-lime",
    bgColor: "bg-zen-lime/10",
    borderColor: "border-zen-lime/30",
    ringColor: "ring-zen-lime/30",
    url: "https://blissroms.org/",
    icon: "/crom-logos/rom/blissroms.png",
  },
  {
    slug: "voltageos",
    name: "VoltageOS",
    type: "rom",
    tagline: "Pure AOSP — simple, secure, performant",
    description:
      "A simplistic, no-frills pure AOSP experience with the right dab of customizations, security patches, and privacy features.",
    longDescription:
      "VoltageOS delivers a simplistic, no-frills pure AOSP experience that won't let you down in getting through every day uninterrupted. With just the right amount of customizations, latest security patches from Google, sandboxed Google Play inspired by GrapheneOS, and Monet theme support, it strikes the perfect balance between simplicity and functionality. Perfect for users who want a clean, secure, and performant daily driver.",
    benefits: [
      "Pure AOSP — no bloatware or unnecessary modifications",
      "Latest security patches as soon as Google releases them",
      "Sandboxed Google Play for enhanced privacy (GrapheneOS-inspired)",
      "Google Monet theming support",
      "Clean, performant daily driver experience",
    ],
    features: [
      "Pure AOSP experience",
      "Sandboxed Google Play",
      "Monet theme engine",
      "Latest security patches",
      "Performance optimizations",
      "Active community & maintainers",
    ],
    color: "text-zen-rose",
    bgColor: "bg-zen-rose/10",
    borderColor: "border-zen-rose/30",
    ringColor: "ring-zen-rose/30",
    url: "https://www.voltageos.com/",
    icon: "/crom-logos/rom/voltageos.png",
  },
  {
    slug: "grapheneos",
    name: "GrapheneOS",
    type: "rom",
    tagline: "Security-hardened & privacy-focused mobile OS",
    description:
      "A privacy and security-focused mobile OS with applied security hardening, exploit mitigations, and Sandboxed Google Play compatibility.",
    longDescription:
      "GrapheneOS is a private and secure mobile operating system with special emphasis on security and privacy. It's based on the Android Open Source Project with significant hardening of the privacy and security model. Running on Google Pixel devices, it provides extensive exploit mitigations, a hardened memory allocator, a sandboxed Google Play compatibility layer, and a robust verified boot chain. GrapheneOS is the gold standard for mobile security, used by journalists, activists, and security-conscious individuals worldwide.",
    benefits: [
      "Industry-leading security hardening and exploit mitigations",
      "Full Google Play compatibility via sandboxed environment",
      "No tracking, telemetry, or data collection",
      "Verified boot chain with secure enclave integration",
      "Timely security updates — often faster than Google",
    ],
    features: [
      "Hardened memory allocator (Scudo)",
      "Sandboxed Google Play support",
      "Vanadium hardened web browser",
      "Attestation & verification tools",
      "Secure contact discovery",
      "Permission auto-reset & network permission",
    ],
    color: "text-zen-gray",
    bgColor: "bg-zen-gray/10",
    borderColor: "border-zen-gray/30",
    ringColor: "ring-zen-gray/30",
    url: "https://grapheneos.org/",
    icon: "/crom-logos/rom/grapheneos.png",
  },
  {
    slug: "superioros",
    name: "SuperiorOS",
    type: "rom",
    tagline: "Elevate your Android experience with AOSP",
    description:
      "An AOSP-based custom ROM offering lightning-fast performance, extensive customization, and rock-solid stability.",
    longDescription:
      "SuperiorOS is an AOSP-based custom ROM designed to elevate your Android experience. It focuses on delivering lightning-fast performance, extensive customization options, and rock-solid stability. Developed by a passionate team, SuperiorOS aims to provide users with a premium Android experience that balances speed, features, and reliability.",
    benefits: [
      "Lightning-fast performance optimizations",
      "Extensive customization options",
      "Rock-solid stability for daily use",
      "Clean AOSP base with thoughtful enhancements",
      "Active development and community support",
    ],
    features: [
      "AOSP-based clean experience",
      "Performance-tuned kernel",
      "Extensive UI customization",
      "Stable daily driver quality",
      "Regular updates & security patches",
      "Active community & support",
    ],
    color: "text-zen-indigo",
    bgColor: "bg-zen-indigo/10",
    borderColor: "border-zen-indigo/30",
    ringColor: "ring-zen-indigo/30",
    url: "https://superioros.github.io/",
    icon: "/crom-logos/rom/superioros.png",
  },
  {
    slug: "linuxmint",
    name: "Linux Mint",
    type: "os",
    tagline: "Elegant, comfortable & free desktop OS",
    description:
      "A free, open-source Linux distribution designed for ease of use, comfort, and out-of-the-box productivity for everyday computing.",
    longDescription:
      "Linux Mint is a community-driven Linux distribution based on Ubuntu, focused on making modern, secure and elegant desktop operating systems that are powerful and easy to use. It comes with a variety of desktop environments and built-in applications, providing a comfortable experience for newcomers and power users alike. Built on the shoulders of Debian and Ubuntu, Linux Mint is one of the most popular desktop Linux distributions in the world for good reason — it just works.",
    benefits: [
      "Free and open-source — no cost, no ads, no telemetry",
      "Easy to install and ideal for Linux newcomers",
      "Built-in multimedia codecs and everyday apps out of the box",
      "Based on the rock-solid Ubuntu/Debian foundation",
      "Active community with long-term support releases",
    ],
    features: [
      "Cinnamon, MATE & Xfce desktop environments",
      "Update Manager with safe, curated updates",
      "Software Manager for easy app installation",
      "Timeshift system snapshots & rollback",
      "Dark mode and desktop theming",
      "Long-term support (LTS) releases",
    ],
    color: "text-zen-green",
    bgColor: "bg-zen-green/10",
    borderColor: "border-zen-green/30",
    ringColor: "ring-zen-green/30",
    url: "https://linuxmint.com/",
    icon: "/crom-logos/linux/linuxmint.png",
  },
  {
    slug: "archlinux",
    name: "Arch Linux",
    type: "os",
    tagline: "A simple, lightweight, rolling-release Linux distro",
    description:
      "An independently developed, x86-64 general-purpose Linux distribution that strives to provide the latest stable versions of most software through a rolling-release model.",
    longDescription:
      "Arch Linux is an independently developed, lightweight and flexible Linux distribution driven by the KISS (Keep It Simple, Stupid) principle. It uses a rolling-release model, so you always run the latest stable software with no upgrade cycles or version jumps. With the Arch User Repository (AUR) and the pacman package manager, Arch is highly customizable — you build your system from the ground up, choosing exactly what you want. It is ideal for users who want to learn how Linux works and take full control of their environment.",
    benefits: [
      "Rolling release — always the latest software",
      "Minimal base you build out exactly how you want",
      "AUR — one of the largest package collections available",
      "Extensive, community-maintained Arch Wiki documentation",
      "Full control and transparency over your system",
    ],
    features: [
      "pacman package manager with powerful dependency handling",
      "Arch User Repository (AUR) for community packages",
      "Rolling-release updates — no version upgrades needed",
      "Minimal, KISS-driven base install",
      "Systemd init and the Arch Wiki",
      "Highly customizable for advanced users",
    ],
    color: "text-zen-sky",
    bgColor: "bg-zen-sky/10",
    borderColor: "border-zen-sky/30",
    ringColor: "ring-zen-sky/30",
    url: "https://archlinux.org/",
    icon: "/crom-logos/linux/archlinux.png",
  },
  {
    slug: "cachyos",
    name: "CachyOS",
    type: "os",
    tagline: "A performance-optimized, Arch-based Linux distro",
    description:
      "An Arch Linux-based distribution focused on optimization, performance and usability, shipping with the latest available kernels and a tuned desktop out of the box.",
    longDescription:
      "CachyOS is a performance-focused Linux distribution based on Arch Linux. It is designed for both desktop users and gamers, offering a smooth, responsive and highly tuned experience. CachyOS ships with optimized kernels (including the CachyOS kernel), BORE scheduler, and performance packages while staying compatible with the Arch ecosystem. It provides a curated installer, a zen browser, and multiple desktop environments, making it an excellent choice for users who want Arch's flexibility with performance optimizations out of the box.",
    benefits: [
      "Performance-tuned kernels and scheduler for speed",
      "Arch-based — full access to AUR and pacman",
      "Gaming optimizations built in out of the box",
      "Curated, easy-to-use graphical installer",
      "Multiple desktop environments to choose from",
    ],
    features: [
      "Optimized CachyOS kernel with BORE scheduler",
      "Compatible with Arch packages and the AUR",
      "Hardware-accelerated and tuned packages",
      "CachyOS zen browser and tools",
      "Rolling-release updates from Arch",
      "Gaming-focused performance optimizations",
    ],
    color: "text-zen-sky",
    bgColor: "bg-zen-sky/10",
    borderColor: "border-zen-sky/30",
    ringColor: "ring-zen-sky/30",
    url: "https://cachyos.org/",
    icon: "/crom-logos/linux/cachyos.png",
  },
  {
    slug: "ubuntu",
    name: "Ubuntu",
    type: "os",
    tagline: "The most popular, user-friendly Linux distro",
    description:
      "A free, open-source Linux distribution based on Debian, known for its ease of use, regular LTS releases and a huge ecosystem of apps and support.",
    longDescription:
      "Ubuntu is the world's most popular Linux distribution, developed by Canonical and the Ubuntu community. Built on the rock-solid Debian foundation, Ubuntu is designed to be easy to use, stable and secure, making it a great choice for laptops, desktops and servers alike. It ships with a large selection of preinstalled applications, the intuitive GNOME desktop, and long-term support (LTS) releases supported for five years. With enormous community support, vast documentation and broad hardware compatibility, Ubuntu is the go-to introduction to Linux for millions of users.",
    benefits: [
      "Huge community, documentation and support",
      "Widely compatible with hardware and software",
      "LTS releases supported for 5 years",
      "Easy installation and everyday usability",
      "Huge software repository and Snap ecosystem",
    ],
    features: [
      "The fast and user-friendly GNOME desktop",
      "Ubuntu Software Center with thousands of apps",
      "Long-term support (LTS) releases",
      "Snap packaging and the Snap Store",
      "Secure and reliable Debian base",
      "Broad device and driver compatibility",
    ],
    color: "text-zen-orange",
    bgColor: "bg-zen-orange/10",
    borderColor: "border-zen-orange/30",
    ringColor: "ring-zen-orange/30",
    url: "https://ubuntu.com/",
    icon: "/crom-logos/linux/ubuntu.png",
  },
  {
    slug: "omarchy",
    name: "Omarchy",
    type: "os",
    tagline: "A comfortable, Arch-based Linux for everyone",
    description:
      "An Arch Linux-based distribution built around the GNUstep ecosystem, focusing on comfort, simplicity and an approachable experience for new users.",
    longDescription:
      "Omarchy is a friendly, Arch-based Linux distribution designed to feel comfortable even for users new to Linux. It emphasizes a clean, intuitive experience while retaining the power and flexibility of the Arch foundation. Ideal for desktops and laptops, Omarchy ships with a curated set of tools and applications so you can get productive quickly without a steep learning curve. Its focus on comfort and approachability makes it a distinctive and welcoming choice in the Linux desktop space.",
    benefits: [
      "Arch-based — full access to pacman and the AUR",
      "Comfortable and approachable for newcomers",
      "Curated tools and apps out of the box",
      "Clean, intuitive desktop experience",
      "Active and friendly community",
    ],
    features: [
      "Built on the Arch Linux foundation",
      "GNUstep-based application ecosystem",
      "Curated default applications",
      "Package management via pacman",
      "Rolling-release model",
      "Approachable, user-focused design",
    ],
    color: "text-zen-orange",
    bgColor: "bg-zen-orange/10",
    borderColor: "border-zen-orange/30",
    ringColor: "ring-zen-orange/30",
    url: "https://omarchy.org/",
    icon: "/crom-logos/linux/omarchy.png",
  },
  {
    slug: "lubuntu",
    name: "Lubuntu",
    type: "os",
    tagline: "An Ubuntu-based distro with a light, fast LXQt desktop",
    description:
      "A fast and lightweight Ubuntu-based Linux distribution using the LXQt desktop environment, perfect for older or resource-limited computers.",
    longDescription:
      "Lubuntu is an official Ubuntu flavor built around the lightweight LXQt desktop environment. Designed to be fast and energy-efficient, it performs wonderfully on older and low-spec hardware while still looking modern and clean. Because it's Ubuntu-based, Lubuntu offers broad software compatibility plus long-term support (LTS) releases. It's an excellent choice for reviving old machines, daily basic computing, or anyone who prefers a lean and snappy desktop without sacrificing functionality.",
    benefits: [
      "Lightweight and fast — great for low-spec hardware",
      "Ubuntu-based with huge software compatibility",
      "Low system resource usage and energy efficient",
      "LTS releases with long support",
      "Clean, modern LXQt desktop",
    ],
    features: [
      "The lightweight LXQt desktop environment",
      "Based on Ubuntu with easy app installation",
      "Optimized for older and low-end computers",
      "Long-term support (LTS) releases",
      "Fast boot and responsive performance",
      "Full-fledged office and multimedia apps available",
    ],
    color: "text-zen-sky",
    bgColor: "bg-zen-sky/10",
    borderColor: "border-zen-sky/30",
    ringColor: "ring-zen-sky/30",
    url: "https://lubuntu.me/",
    icon: "/crom-logos/linux/lubuntu.png",
  },
  {
    slug: "kubuntu",
    name: "Kubuntu",
    type: "os",
    tagline: "An Ubuntu-based distro with the full KDE Plasma experience",
    description:
      "An official Ubuntu flavor combining the stability of Ubuntu with the powerful, feature-rich KDE Plasma desktop and the KDE ecosystem of applications.",
    longDescription:
      "Kubuntu is an official Ubuntu flavor that pairs the reliability, security and LTS support of Ubuntu with the full-featured KDE Plasma desktop environment. Plasma is known for its modern design, deep customization and productivity features, making Kubuntu a powerful and flexible operating system for both work and play. Backed by Ubuntu's extensive software and LTS release model, Kubuntu provides a polished, stable desktop that can be tailored exactly to your tastes — ideal for users who want maximum control and a rich out-of-the-box experience.",
    benefits: [
      "Ubuntu stability with KDE Plasma desktop",
      "Deeply customizable and feature-rich UI",
      "Full KDE application ecosystem included",
      "Long-term support (LTS) releases",
      "Great performance with modern hardware",
    ],
    features: [
      "The KDE Plasma desktop environment",
      "Based on Ubuntu with LTS releases",
      "Hundreds of KDE apps for every task",
      "Extensive theming and customization",
      "Discover software center for easy installs",
      "Powerful search, notifications and workspaces",
    ],
    color: "text-zen-blue",
    bgColor: "bg-zen-blue/10",
    borderColor: "border-zen-blue/30",
    ringColor: "ring-zen-blue/30",
    url: "https://kubuntu.org/",
    icon: "/crom-logos/linux/kubuntu.png",
  },
  {
    slug: "gentoo",
    name: "Gentoo",
    type: "os",
    tagline: "A highly customizable, source-based Linux distro",
    description:
      "A flexible, source-based Linux distribution known for efficiency, customizability and the Portage package management system.",
    longDescription:
      "Gentoo is a powerful and highly customizable Linux distribution built on a source-based model using the Portage package manager. Everything is compiled from source and tuned specifically for your hardware, giving you maximum performance and complete control over your system. This do-it-yourself approach makes Gentoo ideal for power users and those eager to learn how Linux really works under the hood. It offers a rolling-release model, hardened profiles, and near-total flexibility — at the cost of a steeper learning curve and longer compile times.",
    benefits: [
      "Best-in-class performance tuned to your hardware",
      "Total control over every installed package",
      "Rolling release with the latest software",
      "USE flags for fine-grained customization",
      "Excellent for learning Linux internals",
    ],
    features: [
      "The Portage package management system",
      "Source-based compilation and USE flags",
      "Highly configurable kernel and system",
      "Rolling-release updates",
      "Full control over what is installed",
      "Advanced documentation (Gentoo Wiki)",
    ],
    color: "text-zen-purple",
    bgColor: "bg-zen-purple/10",
    borderColor: "border-zen-purple/30",
    ringColor: "ring-zen-purple/30",
    url: "https://www.gentoo.org/",
    icon: "/crom-logos/linux/gentoo.png",
  },
  {
    slug: "voidlinux",
    name: "Void Linux",
    type: "os",
    tagline: "An independent, rolling-release Linux distro",
    description:
      "An independent, lightweight, rolling-release Linux distribution using the runit init system and the xbps package manager.",
    longDescription:
      "Void Linux is an independent, general-purpose Linux distribution that is rolling-release and designed to be fast and stable. It is one of the few major distributions to use the runit init system instead of systemd, and it manages packages with the powerful xbps package manager. Void prides itself on minimalism and simplicity — it is lightweight, highly scriptable and free of corporate influence. This makes it a favorite among users who want a clean, transparent, do-it-yourself system with the flexibility to install nearly anything they need.",
    benefits: [
      "Independent and free of corporate influence",
      "Rolling release with up-to-date software",
      "Fast boot and lightweight by design",
      "runit init system — simple and reliable",
      "Clean, transparent and highly scriptable",
    ],
    features: [
      "The xbps package manager",
      "runit init system (no systemd)",
      "Rolling-release model",
      "Binary packages plus XBPS source builds",
      "Musl and glibc variants available",
      "Minimal and highly customizable",
    ],
    color: "text-zen-green",
    bgColor: "bg-zen-green/10",
    borderColor: "border-zen-green/30",
    ringColor: "ring-zen-green/30",
    url: "https://voidlinux.org/",
    icon: "/crom-logos/linux/voidlinux.png",
  },
  {
    slug: "kali",
    name: "Kali Linux",
    type: "os",
    tagline: "The go-to Linux distro for security and pentesting",
    description:
      "A Debian-based Linux distribution packed with hundreds of tools for digital forensics and penetration testing, maintained by Offensive Security.",
    longDescription:
      "Kali Linux is a Debian-based Linux distribution designed specifically for digital forensics and penetration testing. It comes preloaded with over 600 security tools for tasks such as network analysis, vulnerability scanning, password cracking and wireless auditing. Maintained and funded by Offensive Security, Kali is the industry-standard platform for ethical hacking, security research and professional penetration testing. With modes tailored for ARM devices, WSL, cloud and containers, Kali is portable and flexible across a wide range of workflows.",
    benefits: [
      "Preloaded with 600+ security tools",
      "Debian-based with broad package compatibility",
      "Industry standard for pentesting and forensics",
      "Runs on ARM, WSL, cloud and containers",
      "Rolling-release model with frequent updates",
    ],
    features: [
      "Hundreds of preinstalled pentesting tools",
      "Based on the stable Debian foundation",
      "Single-user root-by-default design",
      "Live boot and installable images",
      "Support for ARM and embedded devices",
      "Extensive documentation and training",
    ],
    color: "text-zen-blue",
    bgColor: "bg-zen-blue/10",
    borderColor: "border-zen-blue/30",
    ringColor: "ring-zen-blue/30",
    url: "https://www.kali.org/",
    icon: "/crom-logos/linux/kali.png",
  },
  {
    slug: "parrot",
    name: "Parrot OS",
    type: "os",
    tagline: "A security-focused Debian-based Linux distro",
    description:
      "A Debian-based Linux distribution designed for security, privacy and development, combining a full cybersecurity toolbox with an approachable daily desktop.",
    longDescription:
      "Parrot OS is a Debian-based Linux distribution focused on security, privacy and development. It ships with a comprehensive suite of cybersecurity tools for penetration testing, digital forensics, reverse engineering and anonymity, while also serving as a polished and usable daily desktop. Backed by a rolling-release model and update channels for both security and development, Parrot balances powerful hacking capabilities with an easy-to-use, privacy-conscious experience — popular among security researchers, students and privacy advocates alike.",
    benefits: [
      "Comprehensive cybersecurity toolkit included",
      "Debian-based with broad compatibility",
      "Privacy and anonymity tools built in",
      "Polished, approachable daily desktop",
      "Rolling-release model with regular updates",
    ],
    features: [
      "Hundreds of security and pentesting tools",
      "Based on the stable Debian foundation",
      "Anonymity and privacy-focused utilities",
      "Clean MATE desktop by default",
      "Live and installable editions",
      "Development, forensics and reverse-engineering tools",
    ],
    color: "text-zen-green",
    bgColor: "bg-zen-green/10",
    borderColor: "border-zen-green/30",
    ringColor: "ring-zen-green/30",
    url: "https://parrotsec.org/",
    icon: "/crom-logos/linux/parrot.png",
  },
  {
    slug: "popos",
    name: "Pop!_OS",
    type: "os",
    tagline: "A polished Ubuntu-based OS for creators & gamers",
    description:
      "A free, open-source Linux distribution from System76, based on Ubuntu with a sleek COSMIC desktop optimized for developers, makers and gamers.",
    longDescription:
      "Pop!_OS is a free and open-source Linux distribution by System76, built on the rock-solid Ubuntu foundation. It pairs a polished, productivity-focused COSMIC desktop with automatic window tiling, streamlined workspaces and out-of-the-box support for modern GPUs — making it a favorite among developers, creators and gamers. With intelligent hardware detection, easy graphics switching and a big, well-curated app store, Pop!_OS is designed to get out of your way so you can focus. System76 is already building the next COSMIC desktop from scratch in Rust.",
    benefits: [
      "Ubuntu-based with outstanding stability",
      "Automatic window tiling and workspaces",
      "Easy hybrid graphics switching out of the box",
      "Great out-of-the-box experience for gaming",
      "Free and open-source from System76",
    ],
    features: [
      "The COSMIC desktop environment",
      "Based on Ubuntu with access to its ecosystem",
      "Automatic tiling and keyboard-driven workflow",
      "Hybrid graphics mode switching",
      "Curated Pop!_Shop for app installation",
      "Built-in disk encryption option",
    ],
    color: "text-zen-orange",
    bgColor: "bg-zen-orange/10",
    borderColor: "border-zen-orange/30",
    ringColor: "ring-zen-orange/30",
    url: "https://system76.com/pop",
    icon: "/crom-logos/linux/popos.png",
  },
  {
    slug: "orangefox",
    name: "OrangeFox",
    type: "tools",
    tagline: "A powerful custom recovery for Android",
    description:
      "A feature-rich custom recovery built on TeamWin Recovery Project, designed for easy flashing, backup, restore and device management.",
    longDescription:
      "OrangeFox is a modern custom recovery for Android devices, based on the popular TeamWin Recovery Project (TWRP). It offers a clean and colorful interface with a wide range of features including nandroid backups, ZIP and image flashing, file management, theme support and an integrated terminal. Because it is open source and supports many devices, OrangeFox is a go-to tool for flashing custom ROMs, rooting devices, and recovering from soft-bricked Android phones.",
    benefits: [
      "Full nandroid backup and restore",
      "Easy flashing of ROMs, kernels and mods",
      "Supports many devices and kernels",
      "Open source and actively maintained",
      "Themes and customizable interface",
    ],
    features: [
      "ZIP and image install support",
      "Nandroid backup and restore",
      "File manager and terminal",
      "Sideload and ADB support",
      "Theme engine and customization",
      "Based on TeamWin Recovery (TWRP)",
    ],
    color: "text-zen-orange",
    bgColor: "bg-zen-orange/10",
    borderColor: "border-zen-orange/30",
    ringColor: "ring-zen-orange/30",
    url: "https://orangefox.tech/",
    icon: "/crom-logos/rom/orangefox.png",
  },
  {
    slug: "ventoy",
    name: "Ventoy",
    type: "tools",
    tagline: "A multi-boot USB tool for OSs and ISOs",
    description:
      "An open-source tool that creates a bootable USB drive where you can simply copy and paste ISO files and boot them directly — no reformatting needed.",
    longDescription:
      "Ventoy is a free and open-source tool that turns a USB drive into a multi-boot device. Instead of flashing ISOs one by one, you simply copy your ISO, WIM, IMG, VHD(x) and EFI files onto the drive, and Ventoy presents a boot menu of everything on it. It supports many operating systems and images, works on both BIOS and UEFI systems, and lets you add or remove bootable images at any time without reformatting. Ventoy is an invaluable tool for anyone who frequently installs operating systems or maintains bootable rescue media.",
    benefits: [
      "Boot multiple ISOs from a single USB drive",
      "Just copy files — no reformatting to add more",
      "Works with Windows, Linux, and more",
      "Supports BIOS and UEFI boot modes",
      "Free and open source",
    ],
    features: [
      "Copy-and-paste ISO booting",
      "Multi-boot menu for many images at once",
      "Supports ISO, WIM, IMG, VHD(x) and EFI",
      "Secure Boot and persistence support",
      "Cross-platform installer",
      "Encrypted and legacy boot modes",
    ],
    color: "text-zen-orange",
    bgColor: "bg-zen-orange/10",
    borderColor: "border-zen-orange/30",
    ringColor: "ring-zen-orange/30",
    url: "https://www.ventoy.net/en/index.html",
    icon: "/crom-logos/linux/ventoy.png",
  },
  {
    slug: "balenaetcher",
    name: "balenaEtcher",
    type: "tools",
    tagline: "Flash OS images to USB & SD cards easily",
    description:
      "A free, cross-platform utility that flashes operating system images to SD cards and USB drives quickly, safely and with simple validation.",
    longDescription:
      "balenaEtcher is a free and open-source cross-platform utility for flashing operating system images to SD cards and USB flash drives. It features a clean and user-friendly interface that lets you select an image, choose a drive, and flash it with a single click. Etcher validates the image after flashing to ensure everything was written correctly, protecting you from corrupt installs. Available on Windows, macOS and Linux, Etcher is the go-to tool for preparing Raspberry Pi cards, live USB sticks and many other bootable media.",
    benefits: [
      "Simple, three-step flashing workflow",
      "Cross-platform (Windows, macOS, Linux)",
      "Automatic post-flash integrity validation",
      "Safe and reliable image writing",
      "Free and open source",
    ],
    features: [
      "Simple select-image, select-drive, flash flow",
      "Post-flash validation to prevent corruption",
      "Supports ISO, IMG and compressed images",
      "Discourages flashing to system drives",
      "Cross-platform compatibility",
      "Lightweight and easy to use",
    ],
    color: "text-zen-gray",
    bgColor: "bg-zen-gray/10",
    borderColor: "border-zen-gray/30",
    ringColor: "ring-zen-gray/30",
    url: "https://etcher.balena.io/",
    icon: "/crom-logos/linux/balenaetcher.png",
  },
]

export function getRom(slug: string): Rom | undefined {
  return roms.find((r) => r.slug === slug)
}
